# Python 1.9 - Numpy

Using numpy for math operations (create array, matrices, indexing and slicing, math operations)<br>

In [1]:
%matplotlib inline
#%matplotlib
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Create an array with numpy
v = np.array([1,2,3,4])
print(v)


[1 2 3 4]


In [3]:
# Get the dimensions of the array, as a tuple
print('Shape = ' + str(v.shape))

Shape = (4,)


In [4]:
# Get the dimension of the array (first index) as a number 
print(v.shape[0])

4


In [5]:
# Simple operations with arrays
v1 = np.array([4,3,2,1])
v2 = np.array([2,2,2,2])

v3 = v1+v2
print('Sum = ' +str(v3))

v3 = v1*v2
print('Mult = ' + str(v3))

Sum = [6 5 4 3]
Mult = [8 6 4 2]


In [ ]:
# Plotting arrays (same as with lists)
plt.figure('Emma')
plt.plot(v1,'ro')
plt.show()

In [6]:
# Creating a matrix
m1 = np.array([[1,2,3],[4,5,6]])
print(m1)

# Or

m1 = np.mat([[1,2,3],[4,5,6]])
print(m1)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [7]:
# Simple functions to create matrices
m1 = np.zeros((4,5))
print(m1)

m1 = np.ones((3,3))
print(m1)

m1 = np.eye(4)
print(m1)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [8]:
# Numpy has all the matrix algebra functions: np.dot, np.cross, np.T, 
m1 = np.mat([[1,2,3],[4,5,6],[7,8,9]])
m2 = np.array([6,7,8])
m3 = np.dot(m1,m2)
print(m3)

[[ 44 107 170]]


In [ ]:
# Change shape with reshape(returns an arugment with modified shape) and resize(acts on the object itself)
m1 = np.array([[1,2,3],[4,5,6]])
print(m1)

m2 = m1.reshape((-1,1))
print(m2)

In [ ]:
# Numpy gives many math operations (np.sqrt, np.sqr, np.sin, np.cos, ....)
print(np.sqrt(4))

In [ ]:
# That can be applied on numpy arrays easily
vX = np.linspace(0,100,250) # creates an array of 50 numbers that go from 0 to 100
vY = 4*vX**2
plt.plot(vX,vY,'dr--')
plt.show()

In [ ]:
# Another example with sin
vTheta = np.linspace(0,4*np.pi,100) # create an array of values from 0 to 4*Pi
vY = 4*np.sin(vTheta)

plt.figure(2)
plt.plot(vTheta,vY,'r')
plt.show()

In [ ]:
# Plenty of operations on arrays
v = np.array([1,2,2,1,3,4])
print('Average: ',v.mean())
print('StDev: ',v.std())
print('Max: ',v.max())
print('Min: ',v.min())

In [ ]:
# Boolean operations on arrays
vBool = (v>2)
print(vBool)

vBoolSum = vBool.sum()
print('Sum: ',vBoolSum)

In [ ]:
# Numpy random generation library
a = np.random.randint(5) # generates an integer random number between 0 and 5
a = np.random.rand(5) # generates an array of dimension 5 with random numbers between 0 and 1
a = np.random.rand(3,4) # generates a matrix 3 x 4 of random numbers between 0 and 1
a = np.random.randn(5) # generates an array of dimension 5 with normally distributed numbers (avg=0, stDev=1)

print(a)

### Exercise: montecarlo simulation of product weight
A production line adds 2 ingredients in a package with 2 feeding system<br>
+ Feeding system 1 has a target weight (avg) = 12g and standard deviation 2g
+ Feeding system 2 has a target weight (avg) = 8g and standard deviation 1.5g

The minimum weight of the package needs to be 18g, calculate defects over 10000 products<br>
HINTS:
+ to shift a normal distribution: w = Avg+StDev*Randn
+ to plot an histogram use: plt.hist(w)